#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /secured/login_facebook

google_login:
    path: /secured/login_google

auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout